services:
  immich-kiosk:
    image: ghcr.io/damongolding/immich-kiosk:latest
    container_name: immich-kiosk
    tty: true
    environment:
      - LANG=en_GB
      - TZ=${TZ}
      - KIOSK_IMMICH_URL=${KIOSK_IMMICH_URL}
      - KIOSK_IMMICH_API_KEY=${KIOSK_IMMICH_API_KEY}
    ports:
      - 2284:3000
    volumes:
      - ./config.yaml:/config.yaml
    restart: always
