services:
  wallos:
    container_name: wallos
    image: bellamy/wallos:latest
    ports:
      - "8282:80/tcp"
    environment:
      TZ: "Europe/Brussels"
    volumes:
      - "./appdata/wallos/db:/var/www/html/db"
      - "./appdata/wallos/logos:/var/www/html/images/uploads/logos"
    restart: unless-stopped
