services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie
    container_name: mealie
    restart: unless-stopped
    ports:
      - "9925:9000"
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      - ./appdata/mealie/data:/app/data/
    environment:
      - ALLOW_SIGNUP=false
      - TZ=${TZ}
      - PUID=1000
      - PGID=1000
      - BASE_URL=${BASE_URL}
