services:
  restic-rest-server:
    container_name: restic-rest-server
    image: restic/rest-server:latest
    ports:
      - "8842:8000"
    volumes:
      - /volume1/docker/restic-rest-server/config:/passwords
      - /volume1/backups/restic:/data
    environment:
      PASSWORD_FILE: "/passwords/.htpasswd"
    restart: unless-stopped
